apiVersion: v1
kind: Secret
metadata:
  name: uetodo-rabbitmq-secret
  namespace: uetodo
type: Opaque
data:
  # Username: myuser (base64 encode)
  RABBITMQ_USER: bXl1c2Vy

  # Password: mypassword (base64 encode)
  RABBITMQ_PASS: bXlwYXNzd29yZA==