apiVersion: v1
kind: Service
metadata:
  name: uetodo-rabbitmq-service
  labels:
    app: uetodo-rabbitmq
spec:
  selector:
    app: uetodo-rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP