apiVersion: v1                            # API version cho Service
kind: Service                             # Định nghĩa một Kubernetes Service
metadata:
  name: uetodo-db-service                 # Tên Service để các Pod khác gọi tới (DNS: uetodo-db-service)
  labels:
    app: uetodo-db                        # Nhãn dùng để phân loại Service

spec:
  selector:
    app: uetodo-db                        # Kết nối với Pod có label app: uetodo-db
  ports:
    - protocol: TCP                       # Giao thức TCP dùng cho DB
      port: 5432                          # Cổng mà các Pod khác sẽ truy cập
      targetPort: 5432                    # Cổng thật trong container PostgreSQL
  type: ClusterIP                         # Chỉ cho phép truy cập nội bộ trong cụm (cluster)
