apiVersion: v1                             # API version cho Secret
kind: Secret                                # Loại tài nguyên là Secret (dữ liệu nhạy cảm)
metadata:
  name: uetodo-db-secret                   # Tên của Secret này

type: Opaque                               # Kiểu Secret tổng quát (mặc định, dùng cho key-value)

data:                                      # Dữ liệu ở dạng base64-encoded
  POSTGRES_USER: cG9zdGdyZXM=              # 'postgres' (tên người dùng DB)
  POSTGRES_PASSWORD: cGFzc3dvcmQ=          # 'password' (mật khẩu DB)
  POSTGRES_DB: dWV0b2Rv                    # 'uetodo' (tên database)
