apiVersion: v1
kind: Service
metadata:
  name: uetodo-db-service
  labels:
    app: uetodo-db
spec:
  selector:
    app: uetodo-db
  ports:
    - protocol: TCP
      port: 5432 # Cổng của Service
      targetPort: 5432 # Cổng của container Postgres
  type: ClusterIP # Chỉ truy cập được từ bên trong cụm