apiVersion: v1                              # API version cho Service
kind: Service                               # Loại tài nguyên là Service
metadata:
  name: uetodo-frontend-service             # Tên Service frontend
  namespace: uetodo                         # Namespace chứa Service này

spec:
  selector:
    app: uetodo-frontend                    # Chọn Pod có label này làm backend cho Service
  ports:
    - port: 80                             # Port mà Service expose trong cluster
      targetPort: 80                       # Port thực tế trong container frontend
  type: ClusterIP                          # Service chỉ truy cập nội bộ cluster
