apiVersion: v1                             # API version cho Secret
kind: Secret                              # Loại tài nguyên Secret
metadata:
  name: uetodo-rabbitmq-secret            # Tên Secret
  namespace: uetodo                       # Namespace chứa Secret

type: Opaque                             # Kiểu Secret (dữ liệu dạng key-value base64)

data:
  RABBITMQ_USER: bXl1c2Vy                 # 'myuser' được mã hóa base64

  RABBITMQ_PASS: bXlwYXNzd29yZA==         # 'mypassword' được mã hóa base64
