apiVersion: v1
kind: Secret
metadata:
  name: uetodo-db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # echo -n 'postgres' | base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # echo -n 'password' | base64
  POSTGRES_DB: dWV0b2Rv # echo -n 'uetodo' | base64