apiVersion: apps/v1
kind: Deployment
metadata:
  name: uetodo-rabbitmq
  namespace: uetodo
  labels:
    app: uetodo-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uetodo-rabbitmq
  template:
    metadata:
      labels:
        app: uetodo-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: uetodo-rabbitmq-secret
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: uetodo-rabbitmq-secret
              key: RABBITMQ_PASS